# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/yunion.io/x/log
    steps:
      - checkout
      - run:
          command: |
            go test -v yunion.io/x/log

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
